var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   o            ",
   "                                                                                ",
   "                                                                  yyy           ",
   "                                                   yy      yy    yy!yy          ",
   "                                    o o      yyyy                y!!!y          ",
   "                                                                 yy!yy          ",
   "                                   yyyyy                          yvy           ",
   "                                                                            yy  ",
   "  yy                                      o o                                y  ",
   "  y            o        o                                                    y  ",
   "  y                                      yyyyy                     o       o y  ",
   "  y          yyyyy      o                                                    y  ",
   "  y @       y          y                                         yyyyy       y  ",
   "  yyyy  yyyyyyy  yyyyyyyyyyyyyyyy  yyyyyyyy  yyyyyyyyyy   yyyyyyyyyyyyyyyyyyyy  ",
   "              y oy             y   y                  y     y                   ",
   "              yyyy           y!!!y                   y!!!!!y                    ",
   "                              y!!!y                  y!!!!!y                    ",
   "                              yyyyy                  yyyyyyy                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      y!!y                        yyyyyyy                                    y!y  ",
   "                                      y!!y                     yyyy     yyyy                                 y!y  ",
   "                                      y!!yyyyyyyyyy           yy           yy                                y!y  ",
   "                                      yy!!!!!!!!!!yy         yy             yy                               y!y  ",
   "                                       yyyyyyyyyy!!y         y                                    o   o   o  y!y  ",
   "                                                yy!y         y     o   o                                    yy!y  ",
   "                                                 y!y         y                                yyyyyyyyyyyyyyy!!y  ",
   "                                                 yvy         y     y   y                        !!!!!!!!!!!!!!yy  ",
   "                                                             yy  |   |   |  yy            yyyyyyyyyyyyyyyyyyyyy   ",
   "                                                              yy!!!!!!!!!!!yy            v                        ",
   "                                                               yyyy!!!!!yyyy                                      ",
   "                                               y     y            yyyyyyy        yyy         yyy                  ",
   "                                               y     y                           y y         y y                  ",
   "                                               y     y                             y         y                    ",
   "                                               y     y                             yy        y                    ",
   "                                               yy    y                             y         y                    ",
   "                                               y     y      o  o     y   y         y         y                    ",
   "               yyyyyyy        yyy   yyy        y     y               y   y         y         y                    ",
   "              yy     yy         y   y          y     y     yyyyyy    y   y   yyyyyyyyy       y                    ",
   "             yy       yy        y o y          y    yy               y   y   y               y                    ",
   "     @       y         y        y   y          y     y               y   y   y               y                    ",
   "    yyy      y         y        y   y          y     y               y   yyyyy   yyyyyy      y                    ",
   "    y y      y         y       yy o yy         y     y               y     o     y y         y                    ",
   "!!!!y y!!!!!!y         y!!!!!!yy     yy!!!!!!!!yy    y!!!!!!!!!!     y     =     y y         y                    ",
   "!!!!y y!!!!!!y         y!!!!!yy       yyyyyyyyyy     y!!!!!!!yy!     yyyyyyyyyyyyy yy  o o  yy                    ",
   "!!!!y y!!!!!!y         y!!!!!y    o                 yy!!!!!!yy !                    yy     yy                     ",
   "!!!!y y!!!!!!y         y!!!!!y                     yy!!!!!!yy  !                     yyyyyyy                      ",
   "!!!!y y!!!!!!y         y!!!!!yy       yyyyyyyyyyyyyy!!!!!!yy   !                                                  ",
   "!!!!y y!!!!!!y         y!!!!!!yyyyyyyyy!!!!!!!!!!!!!!!!!!yy    !                                                  ",
   "!!!!y y!!!!!!y         y!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!yy     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        y                                                                     ",
   "                                        y                                                                     ",
   "                                        y                                                                     ",
   "                                        y                                                                     ",
   "                                       yyy                                                                    ",
   "                                       y y                 !!!        !!!  yyy                                ",
   "                                       y y                 !y!        !y!                                     ",
   "                                     yyy yyy                y          y                                      ",
   "                                      y   y                 y   oooo   y       yyy                            ",
   "                                      y   y                 y          y      y!!!y                           ",
   "                                      y   y                 yyyyyyyyyyyy       yyy                            ",
   "                                     yy   yy      y   y      y                                                ",
   "                                      y   yyyyyyyyy   yyyyyyyy              y y                               ",
   "                                      y   y           y                    y!!!y                              ",
   "                                      y   y           y                     yyy                               ",
   "                                     yy   yy          y                                                       ",
   "                                      y   y= = = =    y            yyy                                        ",
   "                                      y   y           y           y!!!y                                       ",
   "                                      y   y    = = = =y     o      yyy       yyy                              ",
   "                                     yy   yy          y                     y!!!y                             ",
   "                              o   o   y   y           y     y                yyv        yyy                   ",
   "                                      y   y           y              y                 y!!!y                  ",
   "                             yyy yyy yyy yyy     o o  y!!!!!!!!!!!!!!y                   vy                   ",
   "                             y yyy y y yyy y          y!!!!!!!!!!!!!!y                                        ",
   "                             y             y   yyyyyyyyyyyyyyyyyyyyyyy                                        ",
   "                             yy           yy                                         yyy                      ",
   "  yyy                         y     y     y                                         y!!!y                yyy  ",
   "  y y                         y    yyy    y                                          yyy                 y y  ",
   "  y                           y    yyy    yyyyyyy                        yyyyy                             y  ",
   "  y                           y           y                              y   y                             y  ",
   "  y                           yy          y                              y y y                             y  ",
   "  y                                       y       |yyyy|    |yyyy|     yyy yyy                             y  ",
   "  y                yyy             o o    y                              y         yyy                     y  ",
   "  y               yyyyy       yy          y                             yyy       y!!!y          y         y  ",
   "  y               oyyyo       y    yyy    y                             y y        yyy          yyy        y  ",
   "  y                yyy        yyyyyyyyyyyyy  y oo y    y oo y    y oo  yy yy                    yyy        y  ",
   "  y      @          y         y           y!!y    y!!!!y    y!!!!y    yy   yy                    y         y  ",
   "  yyyyyyyyyyyyyyyyyyyyyyyyyyyyy           yyyyyyyyyyyyyyyyyyyyyyyyyyyyy     yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  yyy y       ",
   "                                                                                                      y       ",
   "                                                                                                  yyyyy       ",
   "                                                                                                  y           ",
   "                                                                                                  y yyy       ",
   "                          o                                                                       y y y       ",
   "                                                                                             o o oyyy y       ",
   "                   yyy                                                                                y       ",
   "       !  o  !                                                yyyyy yyyyy yyyyy yyyyy yyyyy yyyyy yyyyy       ",
   "       y     y                                                y   y y   y y   y y   y y   y y   y y           ",
   "       y= o  y            y                                   yyy y yyy y yyy y yyy y yyy y yyy y yyyyy       ",
   "       y     y                                                  y y   y y   y y   y y   y y   y y     y       ",
   "       !  o  !            o                                  yyyy yyyyy yyyyy yyyyy yyyyy yyyyy yyyyyyy       ",
   "                                                                                                              ",
   "          o              yyy                              yy                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      yy                                                      ",
   "                   yyy         yyy                                                                            ",
   "                                                                                                              ",
   "                          o                                                     y      y                      ",
   "                                                          yy     yy                                           ",
   "             yyy         yyy         yyy                                 y                  y                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  yyyyyyyyyyy                                                                                                 ",
   "  y         y o yyyyyyyyy o yyyyyyyyy o yy                                                y                   ",
   "  y         y   y       y   y       y   y                 ||                  y     y                         ",
   "  y  @      yyyyy   o   yyyyy   o   yyyyy                                                                     ",
   "  yyyyyyy                                     yyyyy       yy     yy     yyy                                   ",
   "        y=                  =                =y   y                     yyy                                   ",
   "        yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy   y!!!!!!!!!!!!!!!!!!!!!yyy!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.eyports)
  module.eyports = GAME_LEVELS;
